### ISSUE TITLE
Keys URL does not resolve correctly

### ISSUE THREAD

**Issue by bdemers** [okta/okta-jwt-verifier-java#26]
Reported under: 
https://github.com/okta/okta-jwt-verifier-java/commit/470337c184387a0893506981ef28739e42f3b2e7#commitcomment-30819494

cc: @alexturc

**Comment by jbuffin** [comment]
@bdemers looking at release 0.3.2 looks like this should have been in the merge but the commit isn't there. Can you take a look?

**Comment by bdemers** [comment]
Hey @jbuffin,

Thanks for reaching out! But, I'm not sure I'm following.  Are you looking at the commits for the tag? https://github.com/okta/okta-jwt-verifier-java/commits/okta-jwt-verifier-parent-0.3.2

**Comment by jbuffin** [comment]
I think I was looking at the wrong thing. We are running into any issue with 0.3.2 that I thought was this issue. Our issuer url is https://companyname.oktapreview.com but the library is not resolving the keys url endpoint from the well-known configuration. Instead of `/oath/v1/keys`, the library is going to just `/v1/keys`. Rolling back to 0.3.0 fixed the problem. If this is something new, I can open a new issue.

**Comment by bdemers** [comment]
If the issuer is in the format of `https://{domain}` It cannot be validated by this library, it should be in the format of: `https://{domain}/oauth2/{id}` (commonly something like `https://companyname.oktapreview.com/oauth2/default`)
The former is used for logging into your Okta dashboard/admin console.

Lets keep this thread going, what URLs do you have configured, and what `keys` endpoint do you see being used?

Also, we are working on an updated version of this lib if you want to give that a shot:
https://github.com/okta/okta-jwt-verifier-java/tree/major-rev PR #29

**Comment by jbuffin** [comment]
I'll respond via email with some details.

**Comment by bdemers** [comment]
@jbuffin the release is out, it should be available on Maven Central any time now (could be up to two hour before it shows up)
