### ISSUE TITLE
AccessTokenVerifier.decode while ignoring 'audience' field

### ISSUE THREAD

**Issue by ittzik** [okta/okta-jwt-verifier-java#62]
Hi there,

We have a use case where we would like to decode a JWT token while ignoring the `aud` field.

Is it a valid use case? can it somehow be achieved with the latest version?

in case it's not possible -  as a 2nd best, I found functionality in the nodeJs library that we can use:
https://github.com/okta/okta-oidc-js/tree/master/packages/jwt-verifier#how-to-use
where we can pass the audience dynamically to the decode call (rather then to the builder) - is that likely to be part of the Java lib anytime soon?

Thanks

**Comment by bdemers** [comment]
Ignoring the `aud` field goes against Okta's recommendations for validating it's JWT access tokens: https://developer.okta.com/code/dotnet/jwt-validation/

We do have plans to support a list of audiences in the future, i.e. one of the values from a pre-configured list.
For now, if you already know what the audience should be before you parse the token (i.e. in the case of JS JWT verifier), you should construct a single parser instance for each audience and cache them (validating a JWT requires fetching a public key.  These keys are cached in the parser (which is why we recommend reusing the parser instance).

And of course, if you need to do something more complex you could use JJWT (this is the JWT parser we recommend on the JVM)
https://github.com/jwtk/jjwt


Can you tell me more about your use-case? It could help us improve this library, or I might be able to suggest an alternative.

**Comment by ittzik** [comment]
Thanks for your prompt response!

We have multiple Okta applications (each having a dedicated clientId).
So far only a single application was verifying the okta token in our legacy Java back end.
Now there's a need for more applications to do the same.

I think a list of audiences would be great. until then, a single parser instance is indeed what we're implementing now.

**Comment by bdemers** [comment]
The client Id isn't used when validating access tokens, the `iss` and `aud` (along with other standard JWT claims) are validated:
https://github.com/okta/okta-jwt-verifier-java#setting-up-the-library

https://developer.okta.com/docs/guides/validate-access-tokens/java/overview/

**Comment by scott-avery** [comment]
As

> Thanks for your prompt response!
> 
> We have multiple Okta applications (each having a dedicated clientId). So far only a single application was verifying the okta token in our legacy Java back end. Now there's a need for more applications to do the same.
> 
> I think a list of audiences would be great. until then, a single parser instance is indeed what we're implementing now.

As @ittzik said, in reality, we have multiple application under the same issuer and same audience, only the clientId are different.

The library should provide the ability to validate the clientId at the backend server. Otherwise, access token from other application of same org could pass through the validation.
