### ISSUE TITLE
PKCE flow and ID token nonce value?

### ISSUE THREAD

**Issue by timrourke** [okta/okta-jwt-verifier-java#63]
Hi there!

I'm interested in your recommendations about the best way to fetch the OIDC profile data for an authenticated user. My use case is as follows:
- PKCE flow from my React app, using `@okta/okta-react`
- Verify JWTs in my Scala backend app using this library (`okta/okta-jwt-verifier-java`)

What I'd like to do is accomplish the following:
- User logs in to my frontend application using the PKCE flow
- Frontend app attaches the **identity token** JWT to subsequent API requests as an `Authorization: Bearer` header
- Backend rehydrates basic user profile information statelessly by extracting user profile claims information from the ID token itself

However, in order to verify the JWT using `okta/okta-jwt-verifier-java`, I need to [be able to supply a `nonce` value](https://github.com/okta/okta-jwt-verifier-java/blob/master/impl/src/main/java/com/okta/jwt/impl/jjwt/JjwtIdTokenVerifier.java#L46) to compare the expected nonce value I submitted [while requesting an access token](https://developer.okta.com/docs/guides/implement-oauth-for-okta/request-access-token/) with the actual claim on the ID JWT.

Does this imply that I should not be passing around the ID token if I'm using the PKCE flow initiated by my frontend application, and should instead only be sending an **access token JWT** to my backend for verification?

**Comment by timrourke** [comment]
@aravindanranganathan-okta @robertjd why? Could you explain your reasoning?

**Comment by arvindkrishnakumar-okta** [comment]
@timrourke For the Okta JWT Verifier, `nonce` is required to validate an IDToken. Like you noted, it has to match the `nonce` value used to get the token initially. Validating `IDToken` or `AccessToken` boils down to the decision of whether you are using the token to verify `authentication` or `authorization` respectively. In your use case, since the verification/validation of JWT happens in the backend and may not have the `nonce`, I recommended you use access token validation and pass the access token to the backend.

**Comment by zaza** [comment]
@arvindkrishnakumar-okta why is this still open? Are there any changes expected regarding how the lib verifies IDTokens?

@timrourke Did the last comment answer your question? How did you eventually deal with your problem?

**Comment by arvindkrishnakumar-okta** [comment]
@zaza This can be closed. @timrourke If there are any further questions or followups, please feel free to re-open it.

**Comment by anmeng** [comment]
I am encountering the exactly same issue.
AccessToken does not contain enough information to authorize user, so I intended to use **IdToken**.
There is even an Okta developer guide teaching you how to do it:
https://developer.okta.com/docs/guides/validate-id-tokens/main/#decode-the-id-token

But the decode link pointing to **AccessToken** verification.


If we can not know the nonce before decoding **IdToken**, what is the reason [IdTokenVerifier](https://github.com/okta/okta-jwt-verifier-java/blob/master/api/src/main/java/com/okta/jwt/IdTokenVerifier.java) exist in first place?

**Comment by bdemers** [comment]
@anmeng the goal of an access token is authorization.

When validating an ID token the nonce that was used to request the token is used to verify it. We see a similar question sometimes when someone try’s to make one app pass an ID token from one app to another.

For those use cases, access tokens should be used instead.

taking a step back what information are you trying to get out of your access token.
More generally , can you describe your use case a bit, maybe we can point you in the right direction.

**Comment by Sanket-Sakharkar-Mindstix** [comment]
@anmeng 
We have two email forms, but we must consistently use the second one ('email') from the idToken.

Problem: Only the idToken has user information such the uniqueId and fullName & required email. So this way we can't use accessToken.

We creates tokens on the frontend side only. Right now, we manually decode the JWT and pass the nonce. Any better approach instead of just bypassing it?
