### ISSUE TITLE
JUnit with Wiremock - Issuer HTTPS issue

### ISSUE THREAD

**Issue by absaini123** [okta/okta-jwt-verifier-java#83]
### I'm submitting a
  - bug report

### Background info

JjwtAccessTokenVerifierBuilder's build method checks if the issuer in the token is a valid issuer in BaseVerifierBuilderSupport.validate() which calls okta-config-checks JAR's ConfigurationValidator.assertIssuer(). However, when runing the code through a testing scenario, this implementation needs to allow a non HTTPS url as well. 
In my case, I'm referring to https://developer.okta.com/blog/2018/05/02/testing-spring-boot-angular-components#mock-oktas-api-with-wiremock and using Wiremock to mock the HTTP calls, for which I've to send issuer such as "http://localhost:51592/oauth/issuer".

I've earlier also used okta.testing.disableHttpsCheck property which is accepted by Okta Java API SDK and works fine. May be we could use the same property here as well?

### Expected behavior

"okta.testing.disableHttpsCheck" flag should be read and issuer HTTPs check should be disabled if the flag is true.

### What went wrong?

**Error thrown:** Your Okta Issuer URL must start with https. Current value: http://localhost:64301/oauth/issuer. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://bit.ly/finding-okta-domain

### Steps to reproduce

Pass a JWT token with localhost issuer.

### Library Version
0.5.0

**Comment by VitaliiTytarenko-okta** [comment]
@absaini123 
Thanks for your report!
We will investigate this and comment here when there is additional information to share.
Thanks for using Okta!

**Comment by bdemers** [comment]
Hey @absaini123!

The HTTPS requirement is an important part of this library and validating a JWT.  For testing of your application that uses this JWT library (or any other) I'd recommend a couple of other approaches:

* Write unit tests instead of integration tests (avoid making http requests).  You can mock out the behavior you are expecting from this library.  You could either use a mocking library like Mockito, or (a more involved approach) replace the underlying service (using the service loader: https://github.com/okta/okta-jwt-verifier-java/blob/master/api/src/main/java/com/okta/jwt/JwtVerifiers.java#L54-L61)

* If you do need to mock out actual HTTP requests, you can use the same technique we are using for the ITs of this project: https://github.com/okta/okta-jwt-verifier-java/blob/master/integration-tests/src/test/groovy/com/okta/jwt/it/KeyServerITSupport.groovy

We use reuse a static test keystore, to make things a little easier (but you could do this dynamically too, it just depends on what you are integrating with)
https://github.com/okta/okta-jwt-verifier-java/blob/master/integration-tests/src/test/resources/createKeyStore.sh

**Comment by absaini123** [comment]
Thanks @bdemers for the details. This will solve my issue!
